Solve tornado and 7-zip function name conflicts
```
/usr/bin/x86_64-w64-mingw32-ld: lz/tornado/tor_test.o:tor_test.cpp:(.text+0x3320): multiple definition of `MidAlloc'; misc/7-zip/Alloc.o:Alloc.c:(.text+0x2e0): first defined here
/usr/bin/x86_64-w64-mingw32-ld: lz/tornado/tor_test.o:tor_test.cpp:(.text+0x3350): multiple definition of `MidFree'; misc/7-zip/Alloc.o:Alloc.c:(.text+0x310): first defined here
/usr/bin/x86_64-w64-mingw32-ld: lz/tornado/tor_test.o:tor_test.cpp:(.text+0x43c0): multiple definition of `BigAlloc'; misc/7-zip/Alloc.o:Alloc.c:(.text+0x360): first defined here
/usr/bin/x86_64-w64-mingw32-ld: lz/tornado/tor_test.o:tor_test.cpp:(.text+0x4520): multiple definition of `BigFree'; misc/7-zip/Alloc.o:Alloc.c:(.text+0x410): first defined here
collect2: error: ld returned 1 exit status
```