Don't try to compile tornado on non-x86, 64-bit platforms
Tornado tries to cast a 64-bit pointer into a 32-bit integer. This leads
to some exciting errors:

tornado/MatchFinder.cpp:156:47: error: cast from ‘BYTE* {aka unsigned char*}’ to ‘PtrVal {aka unsigned int}’ loses precision [-fpermissive]
     PtrVal fromPtr(BYTE  *p) {return (PtrVal) p;}

Simply don't build it in these circumstances.

However, removing it causes a link failure - symbols MyAlloc and MyFree
are missing. It turns out these names are used by both Tornado and LZMA,
but usually only Tornado's version is linked it. If Tornado is not being
linked in, add the LZMA Alloc.o to provide the symbols.

Signed-off-by: Daniel Axtens <dja@axtens.net>